# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0463_sessionexam_education_group_year'),
        ('assessments', '0005_auto_20190128_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheetaddress',
            name='education_group_year',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
    ]
